FROM centos:centos7

EXPOSE 30000

#Install Java
#COPY ./data/config/repos /etc/yum.repos.d
##WORKDIR "/etc/yum.repos.d"
#RUN yum check-update || { rc=$?; [ "$rc" -eq 100 ] && exit 0; exit "$rc"; }
#RUN yum -y install adoptopenjdk-11-hotspot.x86_64

RUN yum install java-11-openjdk-devel
RUN tar zxvf openjdk-11.0.1_linux-x64_bin.tar.gz
RUN mv jdk-11.0.1 /usr/local/


RUN java -version

#Install and configure Apache
RUN yum -y install httpd mod_ssl
WORKDIR /etc/httpd/conf

COPY ./data/config/httpd/ssl.conf /etc/httpd/conf.d/
COPY ./data/config/httpd/certs/feg-local.crt /etc/pki/tls/certs/feg-local.crt
COPY ./data/config/httpd/certs/feg-local.key /etc/pki/tls/private/feg-local.key

#Add Jar File
COPY onenet-0.0.1-SNAPSHOT.jar /opt/feg-local/backend/

#Create start.sh
ARG SOFIA_URI
ENV SOFIA_URI_ENV=${SOFIA_URI}

RUN touch /opt/scripts/entrypoint.sh
RUN echo "java -jar ./app.jar --sofia.uri=${SOFIA_URI_ENV}" > /opt/scripts/entrypoint.sh
RUN chmod +x /opt/scripts/entrypoint.sh

#Run
ENTRYPOINT ["/opt/scripts/start.sh"]
