version: "3.7"
services:
  sofia-frontend:
    build:
      context: sofia-frontend
      dockerfile: sofia-frontend/Dockerfile_
      args:
        BACKEND_URL: http://onenet-ngsi-ld-dev-server:15503/api
    image: sofia-frontend
    container_name: sofia-frontend
    ports:
      - "5000:80"
    restart: unless-stopped
    networks:
      - sofia
networks:
  sofia:
    external: true
    name: sofia
    driver: bridge
