version: "3.7"
services:
  local_api:
    build:
      context: local-api
      args:
        CENTRAL_REGISTRY: https://onenet-ngsi-ld.eurodyn.com/api
      dockerfile: Dockerfile
    image: local-api
    container_name: local-api
    ports:
      - "30001:30001"
    restart: unless-stopped
