version: "3.7"
services:
  sofiadb:
    image: mariadb:10.5
    command: --default-authentication-plugin=mysql_native_password
    container_name: sofiadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sofia
    volumes:
      - ./mysql-files:/var/lib/mysql
      - ./mysql-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - sofia
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: sofiadb-admin
    environment:
      PMA_HOST: sofiadb
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 300M
    ports:
      - "4801:80"
    restart: unless-stopped
    networks:
      - sofia
  dozzle:
    image: amir20/dozzle
    container_name: sofia-logs
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8080"
    networks:
      - sofia
#  registry-nginx:
#    image: nginx:1.21.4
#    container_name: sofia-registry-nginx
#    command: [nginx-debug, '-g', 'daemon off;']
#    restart: unless-stopped
#    volumes:
#      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "15555:80"
#    networks:
#      - sofia
  sofia-backend:
    build:
      context: sofia-backend
      args:
        DB_IP: sofiadb
        DB_PORT: 3306
        DB_NAME: sofia
        DB_USERNAME: root
        DB_PASSWORD: root
        RMT: https://rmt.ds.unipi.gr
        REDIS_HOST: sofiaredis
        REDIS_PORT: 6379
        REDIS_PASSWORD: cU7bUfAKHmvvs4yg
      dockerfile: sofia-backend/Dockerfile_
    image: sofia-backend
    container_name: sofia-backend
    ports:
      - "15502:15502"
    restart: unless-stopped
    depends_on:
      - sofiaredis
      - sofiadb
    networks:
      - sofia
  sofia-api-gateway:
    build:
      context: sofia-api-gateway
      args:
        ONENET_IP: http://onenet:15545
        SOFIA_IP: http://sofia-backend:15502
      dockerfile: sofia-api-gateway/Dockerfile_
    image: sofia-api-gateway
    container_name: sofia-api-gateway
    ports:
      - "15602:15602"
    restart: unless-stopped
    networks:
      - sofia
  onenet:
    build:
      context: onenet
      args:
        DB_IP: sofiadb
        DB_PORT: 3306
        DB_NAME: sofia
        DB_USERNAME: root
        DB_PASSWORD: root
        SOFIA_URI: http://sofia-backend:15502/api
        ORION_CONSUMER_IP: http://192.168.1.110:1026
        ORION_PROVIDER_IP: http://192.168.1.110:1027
      dockerfile: onenet/Dockerfile_
    image: onenet
    container_name: onenet
    ports:
      - "15545:15545"
    restart: unless-stopped
    depends_on:
      - sofiadb
    networks:
      - sofia
  sofia-frontend:
    build:
      context: sofia-frontend
      dockerfile: sofia-frontend/Dockerfile_
      args:
        BACKEND_URL: http://localhost:15502/api
    image: sofia-frontend
    container_name: sofia-frontend
    ports:
      - "5000:80"
    restart: unless-stopped
    networks:
      - sofia
  sofiaredis:
    image: "redis:alpine"
    container_name: sofiaredis
    command: redis-server --requirepass cU7bUfAKHmvvs4yg
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - sofia
networks:
  sofia:
    name: sofia
    driver: bridge
